//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaylistGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlaylistGenerator.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out.
        /// </summary>
        internal static string ArgumentFileType {
            get {
                return ResourceManager.GetString("ArgumentFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max.
        /// </summary>
        internal static string ArgumentMaxVideoCount {
            get {
                return ResourceManager.GetString("ArgumentMaxVideoCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mode.
        /// </summary>
        internal static string ArgumentPlaylistMode {
            get {
                return ResourceManager.GetString("ArgumentPlaylistMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xml.
        /// </summary>
        internal static string ArgumentXMLPath {
            get {
                return ResourceManager.GetString("ArgumentXMLPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No filetype specified. Available types are: &quot;pls&quot;, &quot;mpcpl&quot;.
        /// </summary>
        internal static string NoFileTypeSpecifiedError {
            get {
                return ResourceManager.GetString("NoFileTypeSpecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No max video count provided.
        /// </summary>
        internal static string NoMaxVideoCountProvided {
            get {
                return ResourceManager.GetString("NoMaxVideoCountProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Mode Specified.
        /// </summary>
        internal static string NoModeSpecifiedError {
            get {
                return ResourceManager.GetString("NoModeSpecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pool information provided.
        /// </summary>
        internal static string NoPoolDataError {
            get {
                return ResourceManager.GetString("NoPoolDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML file does not have root element Playlist.
        /// </summary>
        internal static string NoRootElementError {
            get {
                return ResourceManager.GetString("NoRootElementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No XML Path Specified.
        /// </summary>
        internal static string NoXmlDataError {
            get {
                return ResourceManager.GetString("NoXmlDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regex.
        /// </summary>
        internal static string RegexAttributeName {
            get {
                return ResourceManager.GetString("RegexAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist Generator.
        /// </summary>
        internal static string Usage1 {
            get {
                return ResourceManager.GetString("Usage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates a playlist based on the idea of pools. 
        ///You can feed in directories which to iterate over to generate playlists.
        /// </summary>
        internal static string Usage2 {
            get {
                return ResourceManager.GetString("Usage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:.
        /// </summary>
        internal static string Usage3 {
            get {
                return ResourceManager.GetString("Usage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        internal static string XMLDirectoryElement {
            get {
                return ResourceManager.GetString("XMLDirectoryElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileType.
        /// </summary>
        internal static string XMLFileTypeAttributeName {
            get {
                return ResourceManager.GetString("XMLFileTypeAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        internal static string XMLLocationAttribute {
            get {
                return ResourceManager.GetString("XMLLocationAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max.
        /// </summary>
        internal static string XMLMaxVideosName {
            get {
                return ResourceManager.GetString("XMLMaxVideosName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mode.
        /// </summary>
        internal static string XMLModeAttribute {
            get {
                return ResourceManager.GetString("XMLModeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool.
        /// </summary>
        internal static string XMLPoolElement {
            get {
                return ResourceManager.GetString("XMLPoolElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        internal static string XMLRootElement {
            get {
                return ResourceManager.GetString("XMLRootElement", resourceCulture);
            }
        }
    }
}
